name: Build For Linux 

on: [push]

jobs:
  linux:
   name: Linux-i386
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - run: |
           sudo apt update
           sudo apt install build-essential cmake make g++ clang gcc g++-multilib gcc-multilib -y
           cd project && mkdir build && cd build
           cmake .. && make -j2
           
   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
          name: ebot-legacy-linux
          path: project/build/ebot/ebot.so
